### PR TITLE
[PHP] Fix `date` format serialization

### LINKED ISSUE #5607: [PHP] date format is "Y-m-d\TH:i:sP"
##### Description

`format: date` field is sent with `Y-m-d\TH:i:sP` format, but according to [specification](http://swagger.io/specification/#data-types-12) it should be just `Y-m-d`

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

```yaml
  SpecialDay:
    required:
      - date
      - opening_type
    properties:
      date:
        type: string
        format: date
      opening_type:
        type: string
        enum:
          - delivering
          - opened
          - closed
          - unavailable
```

results in:

```json
{"date":"2017-05-11T00:00:00+08:00","opening_type":"closed"}
```

##### Command line used for generation

`swagger-codegen generate -i swagger.yml -l php --config php-sdk-config.json -o .`

Config:

```json
{
  "modelPackage": "Model",
  "apiPackage": "Api",
  "invokerPackage": "Sdk",
  "variableNamingConvention": "camelCase",
  "gitUserId": "user",
  "gitRepoId": "repo"
}
```

##### Suggest a Fix

As I checked the generated code it currently checks only type of object, so currently the code cannot distinguish between `date` and `date-time`. I suppose some metadata information should be passed together with the `$data` in `ObjectSerializer`

### PR DESCRIPTION
**Pull request by arnested**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fix serialization of `date` property as it was not serialized to full-date in RFC3339 (as per spec) but to a ISO8601 date-time.

I also added some fixes for codestyle of generated code.

Similar issue for C#: #5734.
General issue regarding date serialization: #5531.

Fixes #5607.

### CODE REVIEW

File: samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php [hunk 1]
```diff
@@ -42,23 +42,26 @@ class ObjectSerializer
...
      *
-     * @param mixed $data the data to serialize
+     * @param mixed  $data   the data to serialize
+     * @param string $type   the SwaggerType of the data
+     * @param string $format the format of the Swagger type of the data
      *
      * @return string|object serialized form of $data
      */
-    public static function sanitizeForSerialization($data)
+    public static function sanitizeForSerialization($data, $type = null, $format = null)
```
Comment (gipeshka) [inline samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php]: `$type` seems to be unused

Comment (arnested) [inline samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php]: Yes, you are right.

I think I though that to be generally useful it would not make sense to provide only the format since the format is "just" a property of the type. Maybe I'm planning too much for the future.
