### PR TITLE
[Rust-Server] Use string literal based mime initialization

### LINKED ISSUE #7126: [Rust-Server] it generates broken codes in some cases around mimetypes
##### Description

when the mime type is not a single token, like `application/vnd.github.v3+json`, it produces invalid rust code

##### Swagger-codegen version

e75523a6846f0aa584ada33674744f395b781a7f 

##### Swagger declaration file content or url

https://gist.github.com/KeenS/195f694ce0e0215dc76541f799ba713d

##### Command line used for generation

```
$ java -jar wagger-codegen-cli.jar generate  -v -l rust-server -i swagger.json   -o server
```

##### Steps to reproduce

run the command above and run

##### Related issues/PRs

None

##### Suggest a fix/enhancement

use `"mime/type".parse().unwrap()`. I'll do it.

### PR DESCRIPTION
**Pull request by KeenS**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.  @frol (2017/07) @farcaller (2017/08) @bjgill (2017/12)

### Description of the PR

fixes #7126.

### CODE REVIEW

**Comment by frol** [comment]
LGTM

File: modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RustServerCodegen.java [hunk 1]
```diff
@@ -528,9 +528,8 @@ public CodegenOperation fromOperation(String path, String httpMethod, Operation
         // if "consumes" is defined (per operation or using global definition)
         if (consumes != null && !consumes.isEmpty()) {
             List<Map<String, String>> c = new ArrayList<Map<String, String>>();
-            for (String key : consumes) {
+            for (String mimeType : consumes) {
                 Map<String, String> mediaType = new HashMap<String, String>();
-                String mimeType = processMimeType(key);
 
                 if (mimeType.startsWith("Application/Xml")) {
```
Comment (bjgill) [inline modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RustServerCodegen.java]: I suspect there may be problems - it looks as if later bits of code assume that the `mimetype` has been generated by `processMimeType` - hence this checking against `Application/Xml`.

According to the [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types), mime types are supposed to be case insensitive, but are generally lower case.

Now that we've no longer got `processMimeType`, do we need to be a bit more clever about how we detect the XML mime type?

Otherwise, it looks sensible.

Comment (KeenS) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RustServerCodegen.java]: I think canonicalizing to lowercase will do.
