### PR TITLE
Go fix enum numbers

### LINKED ISSUE #11615: [GO] Invalid code generated when enum contains integers
##### Description

Per [the Golang spec](https://go.dev/ref/spec#Identifiers), the first character in an identifier must be a letter. When an enum contains strings which are numbers (as in IP versions), these are interpolated into invalid code.

##### Swagger-codegen version

3.0.30

##### Swagger declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
paths:
  /test/:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IPAddressTypeEnum'
          description: null
components:
  schemas:
    IPAddressTypeEnum:
      enum:
      - '4'
      - '6'
      type: string
```

##### Command line used for generation

```bash
swagger-codegen generate -i ../schema.yml -l go
```

##### Steps to reproduce

Save above schema into file, run the command in an empty folder, and take a look at `model_ip_address_type_enum.go`. The identifiers start with numbers, which isn't valid in Go.

```golang
// List of IPAddressTypeEnum
const (
	4__IpAddressTypeEnum IpAddressTypeEnum = "4"
	6__IpAddressTypeEnum IpAddressTypeEnum = "6"
)
```

##### Suggest a fix/enhancement

I'm not really sure what the best approach would be. In my specific case, I'm manually changing them to v4 and v6. Maybe prepending an `i` for `i4` and `i6` to indicate integer? It isn't especially pretty either way.

I'm new to this codebase, so if I'm doing something weirdly or misunderstanding the purpose of something, please set me on the right track. Thank you all so much for your work on this project!

### PR DESCRIPTION
**Pull request by aethanol**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
fix #11615
Enum vars that start with numbers, but are typed as strings end up starting with a number which is invalid in golang.

Fixes regression introduced in https://github.com/swagger-api/swagger-codegen/commit/164d45f1d54f8af896fe61ecb428c8bee971ed3c#diff-25213c27f6aedea540837be9a27725ec3a402e84b882164ee3f6595f9e2ffaa0L16
Enum consts must be unique across a package, this is solved by the enum name to be suffixed with the class name.

cc: @antihax @wing328 (you were listed as contributors to the go generators)

### CODE REVIEW

**Comment by aethanol** [comment]
bump maybe @HugoMario ?

File: modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractGoCodegen.java [hunk 1]
```diff
@@ -486,13 +486,10 @@ public String toEnumVarName(String name, String datatype) {
         if ("int".equals(datatype) || "int32".equals(datatype) || "int64".equals(datatype)
                 || "uint".equals(datatype) || "uint32".equals(datatype) || "uint64".equals(datatype)
                 || "float".equals(datatype) || "float32".equals(datatype) || "float64".equals(datatype)) {
-            String varName = name;
```
Comment (aethanol) [inline modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractGoCodegen.java:489]: Golang identifiers can't be prefixed with _*. See fix generated output https://github.com/swagger-api/swagger-codegen/pull/12076/files#diff-e07213988c61a6f77400109f74d3bf2a72aab72499ee220bb02329be26e6e06aL17

**Comment by HugoMario** [comment]
thanks a lot @aethanol !
