### PR TITLE
Bugfix/6391 retrofit wrong order of params

### LINKED ISSUE #6391: [Android] Retrofit CodeGen : @Path must be before @Query
##### Description

With SwaggerCodeGen 2.2.2 (.jar) we have an issue with retrofit,
a query has @Path and @Query params, and when it's generated, some @Query are before the @Path one. But Retrofit crash in this case

sample : 
--------
```
@GET("/users/{name}/images/")
Call<User> getUserImage(@Path("name") String name, @Query("page") int page)
```
will works

but 

```
@GET("/users/{name}/images/")
Call<User> getUserImage(@Query("page") int page, @Path("name") String name)
```
will crash

##### Swagger-codegen version

SwaggerCodeGen 2.2.2 (.jar) 

##### Command line used for generation

generate -i MY_FILE -o OUTPUT_DIR -l java --library=retrofit2 -c specs/myConfigfile.json

### PR DESCRIPTION
**Pull request by giuliopulina**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

Fixes #6391: retrofit2 is crashing when @Query params are defined before @Path param in the api. 
With this change, params are correctly reordered (@Path param are always defined before @Query param).

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

@bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet

### CODE REVIEW

File: samples/client/petstore/java/retrofit/src/test/java/io/swagger/client/api/PetApiTest.java [hunk 1]
```diff
@@ -76,33 +76,6 @@ public void testFindPetsByStatus() throws Exception {
     }
 
     @Test
-    public void testFindPetsByTags() throws Exception {
```
Comment (wing328) [inline samples/client/petstore/java/retrofit/src/test/java/io/swagger/client/api/PetApiTest.java]: @giuliopulina May I know why the test cases for `findPetsByTags` are removed? Is it throwing errors when run locally?

Comment (giuliopulina) [reply samples/client/petstore/java/retrofit/src/test/java/io/swagger/client/api/PetApiTest.java]: yes, I confirm that mvn integration-test was throwing error.

In fact, if I try to call the service: http://petstore.swagger.io/v2/pet/findByTags?tags=friendly

I receive this error:

      <apiResponse>
          <message>something bad happened</message>
          <type>unknown</type>
      </apiResponse>

And also, if I look in swagger UI, I see that this endpoint is deprecated:

image

Comment (wing328) [reply samples/client/petstore/java/retrofit/src/test/java/io/swagger/client/api/PetApiTest.java]: The CIs (Travis, CircleCI) are running a local copy of the Petstore server as the public petstore server contains invalid pet data from time to time (since anyone can update the record).

Please add those tests back and the CI tests should pass.

Comment (giuliopulina) [reply samples/client/petstore/java/retrofit/src/test/java/io/swagger/client/api/PetApiTest.java]: done 👍

**Comment by wing328** [comment]
@giuliopulina I did some tests locally and the result is good. Thanks for the PR.

**Comment by florent37** [comment]
thanks a lot for your work :)

**Comment by mmallis87** [comment]
I have a related question regarding operations path params specifically: does anyone think that we should enforce path params order based on how they appear in on the URL path instead of relying on the order in the `parameters` array?

For instance when the URL path is "/accounts/{accountId}/users/{userId}" and
```
"parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "The external user number (int) or user ID Guid.",
            "required": true,
            "type": "string"
          },
          {
            "name": "accountId",
            "in": "path",
            "description": "The external account number (int) or account ID Guid.",
            "required": true,
            "type": "string"
          }
]
```
the generated method will have a signature that looks like `public void myMethod(String userId, String accountId);`. I think it makes more sense to have `public void myMethod(String accountId, String userId);`. Curious to see what you guys think!

**Comment by giuliopulina** [comment]
> I have a related question regarding operations path params specifically: does anyone think that we should enforce path params order based on how they appear in on the URL path instead of relying on the order in the `parameters` array?
> 
> For instance when the URL path is "/accounts/{accountId}/users/{userId}" and
> 
> ```
> "parameters": [
>           {
>             "name": "userId",
>             "in": "path",
>             "description": "The external user number (int) or user ID Guid.",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "accountId",
>             "in": "path",
>             "description": "The external account number (int) or account ID Guid.",
>             "required": true,
>             "type": "string"
>           }
> ]
> ```
> 
> the generated method will have a signature that looks like `public void myMethod(String userId, String accountId);`. I think it makes more sense to have `public void myMethod(String accountId, String userId);`. Curious to see what you guys think!

Hi @mmallis87 for what my opinion may be worth, I think it can make sense: however, I think this behavior should be aligned between all the different generators, not just for the Retrofit one, so it should be an higher level design decision.

**Comment by mmallis87** [comment]
@giuliopulina I agree that this type of change should be aligned across all generators since it's not specific to Java or Retrofit.
