### PR TITLE
[TypeScript] fix class filename in import/export

### LINKED ISSUE #5136: [TypeScript] fix class filename in import/export
##### Description

Currently, TS generators use {{classname}} instead of {{classFilename}} for import/export.

We've filed https://github.com/swagger-api/swagger-codegen/pull/5131 to fix the issue for TS Angular2 and we need similar fix for TS Node, Fetch, Angular, jQuery (if these templates have the same issue)

##### Swagger-codegen version

Latest master

##### Related issues

https://github.com/swagger-api/swagger-codegen/pull/5131

##### Suggest a Fix

Similar to https://github.com/swagger-api/swagger-codegen/pull/5131

### PR DESCRIPTION
**Pull request by TiFu**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

- Fixes #5136 
- Same changes as in #5131 but for ts-angular.
- Additionally: changed models.mustache of ts-angular2
- Recreated ts-angular & ts-angular2 samples

### CODE REVIEW

File: samples/client/petstore/typescript-angular/api/api.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
...
-import { PetApi }  from './PetApi';
+import { PetApi } from './PetApi';
 export * from './StoreApi';
-import { StoreApi }  from './StoreApi';
+import { StoreApi } from './StoreApi';
 export * from './UserApi';
-import { UserApi }  from './UserApi';
-export const APIS = [ PetApi, StoreApi, UserApi, ];
+import { UserApi } from './UserApi';
+export const APIS = [PetApi, StoreApi, UserApi, ];
```
Comment (wing328) [inline samples/client/petstore/typescript-angular/api/api.ts]: @TiFu FYI. I'll file a PR later to remove the trailing comma.

**Comment by wing328** [comment]
@TiFu thanks for the PR, which looks good to me.

File: samples/client/petstore/typescript-angular/api/api.ts (hunk 1 above)
Comment (wing328) [inline samples/client/petstore/typescript-angular/api/api.ts]: UPDATE: fixed via https://github.com/swagger-api/swagger-codegen/issues/5563
