### PR TITLE
[TypeScript-Angular] Path URI Encoding Update

### LINKED ISSUE #6762: [Typescript-Angular] Service generation incorrectly attempting to use parameter.
##### Description

Upon generating the code for my angular project, I copied it into my app directory. Immediately, the compiler starts spitting out errors about being unable to find variables. This is an example of the exact error (there are a lot of them):

`ERROR in /home/def_monk/code/eve-calendar/src/app/esi/api/wars.service.ts (163,92): Cannot find name 'war_id'.`

It's pretty easy to identify what it's talking about, since the uses of snakecase are very rare in the files. There is a mismatch in the parameter name and what is used in the return statement. The function in which that particular error occurs is here:

```typescript
/**
 * List kills for a war
 * Return a list of kills related to a war  --- Alternate route: &#x60;/v1/wars/{war_id}/killmails/&#x60;  Alternate route: &#x60;/legacy/wars/{war_id}/killmails/&#x60;  Alternate route: &#x60;/dev/wars/{war_id}/killmails/&#x60;  --- This route is cached for up to 3600 seconds
 * @param warId A valid war ID
 * @param datasource The server name you would like data from
 * @param page Which page of results to return
 * @param userAgent Client identifier, takes precedence over headers
 * @param xUserAgent Client identifier, takes precedence over User-Agent
 */
public getWarsWarIdKillmails(warId: number, datasource?: string, page?: number, userAgent?: string, xUserAgent?: string): Observable<Array<GetWarsWarIdKillmails200Ok>> {
    if (warId === null || warId === undefined) {
        throw new Error('Required parameter warId was null or undefined when calling getWarsWarIdKillmails.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (datasource !== undefined) {
        queryParameters = queryParameters.set('datasource', <any>datasource);
    }
    if (page !== undefined) {
        queryParameters = queryParameters.set('page', <any>page);
    }
    if (userAgent !== undefined) {
        queryParameters = queryParameters.set('user_agent', <any>userAgent);
    }

    let headers = this.defaultHeaders;
    if (xUserAgent !== undefined && xUserAgent !== null) {
        headers = headers.set('X-User-Agent', String(xUserAgent));
    }

    return this.httpClient.get<any>(`${this.basePath}/wars/${encodeURIComponent(String(war_id))}/killmails/`,
    {
        params: queryParameters,
        headers: headers,
        withCredentials: this.configuration.withCredentials,
    });
}
```

##### Swagger-codegen version

Master at time of pull:  [f0b7dae](https://github.com/swagger-api/swagger-codegen/tree/f0b7daeec691ea0fb0d48139cc4610b0a49d285b) (which would mean actual version is 2.3.0, if I understand correctly).

##### Swagger declaration file content or url

https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility

##### Command line used for generation

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
	-i https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility \
	-l typescript-angular \
	-o ./clients/esi/
```

##### Steps to reproduce

Generate code, and try to move it into the angular application. The typescript will not be able to compile. I'm used [Angular CLI](https://github.com/angular/angular-cli) to do the project generation and the compile/serve.

##### Related issues/PRs

#4264 seems related, since it looks to be when the change to camelcase was made to match the style guide.

##### Suggest a fix/enhancement

Looking around to try and figure out what the problem was, I eventually made my way to [this line](https://github.com/swagger-api/swagger-codegen/blob/f0b7daeec691ea0fb0d48139cc4610b0a49d285b/modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache#L266) of mustache template for the services. That said, this is my first time using both codegen and angular2+, and I know nothing about using mustache templates, so I have no idea if I'm actually correct in guessing it has something to do with that line of code. Lol. But simply using the camelcase version of the parameter, instead of snakecase, seems like it would fix the error.

### PR DESCRIPTION
**Pull request by defmonk0**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

This update replaces the code for updating paths for URI encoding. Previously, this code was not converting from snake_case to camelCase, causing the variables embedded in the path to not match the parameter names they were passed to the function as.

The new method involves finding matches of items in curly-braces and iterating through them. Each match is then searched through for underscores. If one is found, it is removed and the following letter is capitalized.

The more complicated replacement is necessary to guarantee we only change the format of the variables inside the template braces. Otherwise, it might replace parts of the url/path itself, rather than just the variable names.

This should fix #6762.

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

### CODE REVIEW

File: modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java [hunk 1]
```diff
@@ -247,8 +250,55 @@ public void postProcessParameter(CodegenParameter parameter) {
...
+            Matcher pathMatcher = pathPattern.matcher(op.path);
+
+            // Prep a string buffer where we're going to set up our new version of the string.
+            StringBuffer pathBuffer = new StringBuffer();
+
+            // Iterate through the matches for the regex.
+            // This should be anything that was contained inside curly-braces.
+            while(pathMatcher.find()) {
+                // Get a substring of our match.
+                String templateSection = op.path.substring(pathMatcher.start(), pathMatcher.end());
```
Comment (macjohnny) [inline modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java]: I would choose a simpler implementation like e.g. https://stackoverflow.com/a/34229320

Comment (defmonk0) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java]: Hmm. Looking at it now, I agree. It's been a long while since I've coded in Java, so after seeing the original code used regex, I just did the same in case it needed to be more complicated later. That said, it's definitely not the most efficient. 

I'll mess with this is a bit, I should be able to do this with much simpler string manipulation, crawling through 1 character at a time. I should only need one iteration through the string.

**Comment by defmonk0** [comment]
Rebased on master, and re-pushed the branch with the extra commit.

I simplified the implementation. Much cleaner, and more efficient too. Since using split would have still required avoiding underscores outside of the template braces, I figured this iteration method was simpler in the long run. No regex or secondary iteration required.

**Comment by defmonk0** [comment]
I rebased on master again, so that the tests would pass (since the previous commit this was based on was not). @macjohnny thoughts?

**Comment by wing328** [comment]
@defmonk0 thanks for the PR with detailed comments in the code, which looks good to me.
